### ISSUE TITLE
Images disappear when saving

### ISSUE THREAD

**Issue by MariusCausemann** [node-projects/vs-code-designer-addon#9]
Hi,
I'm using your add-on to quickly arrange images on a html page. It works great, except for one thing: As soon as I save the file, the image isn't rendered anymore... But the html (and file path) seem to be ok, since it is correctly shown in e.g. the vscode html preview add-on or chrome). Any idea what is happening here?
Opening and closing doesn't help, the image isn't rendered after saving the html for the first time.

Before saving:
![swappy-20241206_095738](https://github.com/user-attachments/assets/3aed5b59-6681-46de-8d62-41fd59b06d76)

After saving:
![swappy-20241206_095844](https://github.com/user-attachments/assets/b5496dba-85e5-4ff2-b9d6-d2000e2ba761)

**Comment by jogibear9988** [comment]
Can you share your URLs...
I also tried a fix in the new version, can you check

**Comment by MariusCausemann** [comment]
I just updated to the new version, and the problem is fixed! Thank you so much for such a quick solution!
(My images are local, so no URL to share)
